# .github/workflows/ci-pipeline.yml

name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  # Job de CI (o que já tínhamos)
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci # 'npm ci' é mais rápido e seguro para CI do que 'npm install'

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm test

  # Novo Job de CD: Build e Push da imagem Docker
  build-and-push:
    # Este job só roda se 'build-and-test' for bem-sucedido
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          # Nome da sua imagem no Docker Hub
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/meu-projeto-devops:latest